apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: void-drifter-tls
  namespace: void-drifter
spec:
  secretName: void-drifter-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - void-drifter.romaine.life
