apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: void-drifter-backend-secrets
  namespace: void-drifter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: romaine-kv
    kind: ClusterSecretStore
  target:
    name: void-drifter-backend-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: void-drifter-database-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: void-drifter-postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: SESSION_SECRET
      remoteRef:
        key: void-drifter-session-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: MICROSOFT_CLIENT_ID
      remoteRef:
        key: void-drifter-microsoft-client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: MICROSOFT_CLIENT_SECRET
      remoteRef:
        key: void-drifter-microsoft-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
